using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OrbiNom.Satellites
{
  internal class AmsatNames
  {
    public static string[] SatelliteNames = [
      "AO-123",
      "AO-16",
      "AO-27",
      "AO-7 Mode A",
      "AO-7 Mode B",
      "AO-73",
      "AO-85",
      "AO-91",
      "BHUTAN-1",
      "BO-102",
      "BY70-2",
      "CAS-2T",
      "CAS-4A",
      "CAS-4B",
      "CatSat",
      "CubeBel-1",
      "CUTE-1",
      "DSTAR1",
      "DUCHIFAT1",
      "DUCHIFAT3",
      "EO-79",
      "EO-80",
      "EO-88",
      "ESEO",
      "Falconsat3",
      "FloripaSat 1",
      "FMN-1",
      "FO-118[H/u]",
      "FO-118[V/u FM]",
      "FO-118[V/u]",
      "FO-29",
      "FO-99",
      "GO-32",
      "HA-1",
      "HO-107",
      "HO-113",
      "HO-119",
      "HO-68",
      "IO-117",
      "IO-26",
      "IO-86 ",
      "ISS FM Repeater",
      "ISS Packet/APRS",
      "ISS SSTV",
      "ISS-DATV",
      "JAISAT-1",
      "JO-97",
      "K2SAT",
      "LEDSAT",
      "LilacSat-2",
      "LO-19",
      "LO-87",
      "LO-90",
      "LO-93",
      "LO-94",
      "MAYA-1",
      "MO-122",
      "Neutron-1",
      "NO-103",
      "NO-44",
      "NO-45",
      "NO-61",
      "NO-62",
      "NO-83",
      "NO-84 (PSAT) Digi",
      "NO-84 (PSAT) PSK",
      "OUFTI-1",
      "PicSat",
      "PO-101[APRS]",
      "PO-101[FM]",
      "QIKCOM-1",
      "QO-100 NB",
      "QO-100 WB",
      "QUAKESAT",
      "RS-15",
      "RS-20",
      "RS-25",
      "RS-44",
      "SO-114",
      "SO-115",
      "SO-121",
      "SO-124",
      "SO-33",
      "SO-50",
      "SONATE-2 APRS",
      "SONATE-2 SSTV",
      "SPACECUBE",
      "Taurus-1",
      "TO-108",
      "UBAKUSAT",
      "UiTMSAT-1",
      "UKube-1",
      "UO-11 Mode B",
      "UO-11 Mode S",
      "UVSQ-SAT",
      "UWE-3",
      "VO-96",
      "X-CUBESAT",
      "XI-IV",
      "XI-V",
      "XW-2A",
      "XW-2B",
      "XW-2C",
      "XW-2D",
      ];

    
  }
}